# To build this image: docker build -t collect_kafka# -f Dockerfile.kafka .
# docker run -e KAFKA_SERVER=IP:9092 collect_kafka
# docker run --cap-add=NET_ADMIN -e KAFKA_SERVER=IP:9092 collect_kafka#


FROM ubuntu:20.04
# docker exec -it --privileged container_name tc qdisc add dev eth0 root netem delay 100ms
# Copy script files
COPY kafka_collect_produce.py /app/

WORKDIR /app

# Install system packages using sudo
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk stress && \
    apt-get clean

# Install Python dependencies using sudo
RUN apt-get install -y python3-pip
RUN pip3 install kafka-python
RUN pip3 install confluent-kafka
RUN pip3 install psutil
RUN pip3 install numpy
RUN pip3 install scikit-learn

# Define an environment variable for the Kafka bootstrap server
ENV KAFKA_SERVER="172.16.9.157:9092" 
# specify the IP needed

# Set the entry point
CMD ["python3", "kafka_collect_produce.py", "$KAFKA_SERVER"]
